### ISSUE TITLE
Can we install only weblogic and configure manage server ?

### ISSUE THREAD

**Issue by BhushDevOps** [Stavros/weblogic-ansible#1]
Hey Stavros,

Can we install only weblogic and configure manage server. If yes what are the necessary configuration and update do i need to do in this yml files. 

Thanks in Advance !!!

**Comment by Stavros** [comment]
Hi @aivl2018 ,

You can edit each specific yaml file under each role to configure your things, you can also remove specific roles, if not needed, by opting them out from the main yaml file (weblogic-fmw-domain.yml). By default this ansible script provides a bare minimum environment (Configure OS + install Java + WL + Domain + NodeMngr + ManagedSrv).

Hope it helps.

**Comment by BhushDevOps** [comment]
Thanks Stavros.
